CREATE OR REPLACE PROCEDURE PA_INSERT_DETALLE_FICHA(P_NUMERO_FICHA_FK IN NVARCHAR2,P_CODIGO_CURSO_FK IN VARCHAR2,P_MSG_ERROR OUT VARCHAR2) IS

BEGIN

   INSERT INTO DETALLEFICHA(NUMEROFICHA_FK, CODIGOCURSO_FK)
   VALUES(P_NUMERO_FICHA_FK,P_CODIGO_CURSO_FK);
   COMMIT;
   
     
    exception 
    when no_data_found then
    dbms_output.put_line('no_data_found');
        P_MSG_ERROR:= SQLCODE||' = '||SQLERRM;
    
    when others then
    DBMS_OUTPUT.PUT_LINE('Error: '||SQLCODE||' = '||SQLERRM);
    P_MSG_ERROR:= SQLCODE||' = '||SQLERRM;
    END EXCEPTION;
END;
