package com.ecoinnova.pe.model;

// default package
// Generated 05-oct-2016 16:39:58 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbDetalleBoletaId generated by hbm2java
 */
@Embeddable
public class TbDetalleBoletaId implements java.io.Serializable {

	private String codigoBol;
	private String codigoPro;

	public TbDetalleBoletaId() {
	}

	public TbDetalleBoletaId(String codigoBol, String codigoPro) {
		this.codigoBol = codigoBol;
		this.codigoPro = codigoPro;
	}

	@Column(name = "codigo_bol", nullable = false, length = 20)
	public String getCodigoBol() {
		return this.codigoBol;
	}

	public void setCodigoBol(String codigoBol) {
		this.codigoBol = codigoBol;
	}

	@Column(name = "codigo_pro", nullable = false, length = 20)
	public String getCodigoPro() {
		return this.codigoPro;
	}

	public void setCodigoPro(String codigoPro) {
		this.codigoPro = codigoPro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbDetalleBoletaId))
			return false;
		TbDetalleBoletaId castOther = (TbDetalleBoletaId) other;

		return ((this.getCodigoBol() == castOther.getCodigoBol()) || (this
				.getCodigoBol() != null && castOther.getCodigoBol() != null && this
				.getCodigoBol().equals(castOther.getCodigoBol())))
				&& ((this.getCodigoPro() == castOther.getCodigoPro()) || (this
						.getCodigoPro() != null
						&& castOther.getCodigoPro() != null && this
						.getCodigoPro().equals(castOther.getCodigoPro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodigoBol() == null ? 0 : this.getCodigoBol().hashCode());
		result = 37 * result
				+ (getCodigoPro() == null ? 0 : this.getCodigoPro().hashCode());
		return result;
	}

}
