package ar.edu.unju.fi.apu.modelo.dominio;
// Generated 19/05/2015 14:55:05 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String nombreUsuario;
     private Persona persona;
     private String password;
     private String correoElectronico;
     private boolean estado;

    public Usuario() {
    }

	
    public Usuario(String nombreUsuario, String password, boolean estado) {
        this.nombreUsuario = nombreUsuario;
        this.password = password;
        this.estado = estado;
    }
    public Usuario(String nombreUsuario, Persona persona, String password, String correoElectronico, boolean estado) {
       this.nombreUsuario = nombreUsuario;
       this.persona = persona;
       this.password = password;
       this.correoElectronico = correoElectronico;
       this.estado = estado;
    }
   
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


