package com.ecoinnova.pe.model;

// Generated 29-sep-2016 16:48:26 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbCliente generated by hbm2java
 */
@Entity
@Table(name = "tbCliente", catalog = "bdBodega",  schema = "dbo")
public class TbCliente implements java.io.Serializable {

	private String codigoCli;
	private String rucDniCli;
	private String razonSocialCli;
	private String direccionCli;

	public TbCliente() {
	}

	public TbCliente(String codigoCli) {
		this.codigoCli = codigoCli;
	}

	public TbCliente(String codigoCli, String rucDniCli, String razonSocialCli,
			String direccionCli) {
		this.codigoCli = codigoCli;
		this.rucDniCli = rucDniCli;
		this.razonSocialCli = razonSocialCli;
		this.direccionCli = direccionCli;
	}

	@Id
	@Column(name = "codigo_cli", unique = true, nullable = false, length = 20)
	public String getCodigoCli() {
		return this.codigoCli;
	}

	public void setCodigoCli(String codigoCli) {
		this.codigoCli = codigoCli;
	}

	@Column(name = "ruc_dni_cli", length = 15)
	public String getRucDniCli() {
		return this.rucDniCli;
	}

	public void setRucDniCli(String rucDniCli) {
		this.rucDniCli = rucDniCli;
	}

	@Column(name = "razon_social_cli", length = 150)
	public String getRazonSocialCli() {
		return this.razonSocialCli;
	}

	public void setRazonSocialCli(String razonSocialCli) {
		this.razonSocialCli = razonSocialCli;
	}

	@Column(name = "direccion_cli", length = 150)
	public String getDireccionCli() {
		return this.direccionCli;
	}

	public void setDireccionCli(String direccionCli) {
		this.direccionCli = direccionCli;
	}

}
